#  3 часть

Find non-linear regression and classification models with best hyperparameters.

2. Fit **6** nonlinear models for regression target `__price`: Decision Tree, Random Forest, Hist Gradient Boosting (scikit-learn), LightGBM, XGBoost, CatBoost
    - Find optimal hyperparameters for each model (select more than 10+ experiments for each model)
    - Calculate scores for each experiments and add it to the `scoring_price` table
3. Fit **6** nonlinear models models for target `__churn`: Decision Tree, Random Forest, Hist Gradient Boosting (scikit-learn), LightGBM, XGBoost, CatBoost
    - Find optimal hyperparameters for each model (select more than 10+ experiments for each model)
    - Calculate scores for each experiments and add it to the `scoring_churn` table
4. Select best regression and classification model based on the results in tables `scoring_price` and `scoring_churn`
5. The results of the best models should be saved in the following columns:
    - best_regression_model.predict(): `__price_predict`
    - best_classification_model.predict_proba(): `__churn_prob`
    - algorithm: `__priority`

# Your metrics from experiments

In [1]:
import numpy as np
import pandas as pd

scoring_price = pd.DataFrame([
    # Regression
    ('Decision Tree', '{...}', 'metric_for_price', 0., 0.),
    ('Random Forest', '{...}', 'metric_for_price', 0., 0.),
    ('Hist Gradient Boosting', '{...}', 'metric_for_price', 0., 0.),
    ('LightGBM', '{...}', 'metric_for_price', 0., 0.),
    ('XGBoost', '{...}', 'metric_for_price', 0., 0.),
    ('CatBoost', '{...}', 'metric_for_price', 0., 0.),
], columns=['alg', 'hyperparametes', 'metric_name', 'score_train', 'score_test'])

scoring_price

,alg,hyperparametes,metric_name,score_train,score_test
0,Decision Tree,{...},metric_for_price,0.0,0.0
1,Random Forest,{...},metric_for_price,0.0,0.0
2,Hist Gradient Boosting,{...},metric_for_price,0.0,0.0
3,LightGBM,{...},metric_for_price,0.0,0.0
4,XGBoost,{...},metric_for_price,0.0,0.0
5,CatBoost,{...},metric_for_price,0.0,0.0

In [ ]:
import numpy as np
import pandas as pd

# table with metrics for all models

scoring_churn = pd.DataFrame([
    # Classification
    ('Decision Tree', '{...}', 'metric_for_churn', 0., 0.),
    ('Random Forest', '{...}', 'metric_for_churn', 0., 0.),
    ('Hist Gradient Boosting', '{...}', 'metric_for_churn', 0., 0.),
    ('LightGBM', '{...}', 'metric_for_churn', 0., 0.),
    ('XGBoost', '{...}', 'metric_for_churn', 0., 0.),
    ('CatBoost', '{...}', 'metric_for_churn', 0., 0.),
], columns=['alg', 'hyperparametes', 'metric_name', 'score_train', 'score_test'])

scoring_churn

,alg,hyperparametes,metric_name,score_train,score_test
0,Decision Tree,{...},metric_for_churn,0.0,0.0
1,Random Forest,{...},metric_for_churn,0.0,0.0
2,Hist Gradient Boosting,{...},metric_for_churn,0.0,0.0
3,LightGBM,{...},metric_for_churn,0.0,0.0
4,XGBoost,{...},metric_for_churn,0.0,0.0
5,CatBoost,{...},metric_for_churn,0.0,0.0

In [3]:
import numpy as np
import pandas as pd
pd.options.display.max_rows = 1000

# Your Name Surname
# !!! should not change in other hypotheses
NAME = "Kirill_Viksman"

dataset = pd.read_csv(f"1_{NAME}.csv", index_col=0)
SHAPE = dataset.shape

train_all = dataset[dataset['dtype'] == 'train']
test = dataset[dataset['dtype'] == 'test']

SHAPE, train_all.shape, test.shape

((30471, 399), (20483, 399), (9988, 399))

## Metrics for estimate model quality

In [20]:
%pip install -U scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.8.0-cp314-cp314-macosx_10_15_x86_64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (2.3.5)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-macosx_14_0_x86_64.whl.metadata (62 kB)
Collecting joblib>=1.3.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.8.0-cp314-cp314-macosx_10_15_x86_64.whl (8.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 329.0 kB/s  0:00:25m0:00:0100:02
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading scipy-1.17.1-cp314-cp314-macosx_14_0_x86_64.whl (22.7 MB)
   ━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/22.7 MB 97.6 kB/s eta 0:03:07
WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (4.5 MB/22.7 MB, attempt 1)
Resuming download scipy-1.17.1-cp314-cp314-macosx_14_0_x86_64.whl (4.5 MB/22.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.7/22.7 MB 4.4 MB/s  0:00:04m0:00:0100:01
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [scikit-learn][0m [scikit-learn]
Successfully installed joblib-1.5.3 scikit-learn-1.8.0 scipy-1.17.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:

from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import roc_auc_score

def metric_for_price(y_true, y_pred):
    """ mean_squared_log_error. bigger is better """
    return round(-mean_squared_log_error(y_true=y_true, y_pred=y_pred), 3)


def metric_for_churn(y_true, y_score):
    """ roc_auc_score. bigger is better """
    return round(roc_auc_score(y_true=y_true, y_score=y_score), 3)

# YOUR WORK STARTS HERE

In [23]:
%pip install -U scikit-learn lightgbm xgboost catboost

Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (1.8.0)
Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-macosx_10_15_x86_64.whl.metadata (17 kB)
Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-macosx_10_15_x86_64.whl.metadata (2.1 kB)
Collecting catboost
  Downloading catboost-1.2.10-cp314-cp314-macosx_11_0_universal2.whl.metadata (1.4 kB)
Requirement already satisfied: numpy>=1.24.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.10.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from scikit-learn) (3.6.0)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Collecting matplotlib (from catboost)
  Downloading matplotlib-3.10.8-cp314-cp314-macosx_10_13_x86_64.whl.metadata (52 kB)
Requirement already satisfied: pandas<4.0,>=0.24 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from catboost) (2.3.3)
Collecting plotly (from catboost)
  Downloading plotly-6.7.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: six in /Users/kirillviksman/Library/Python/3.14/lib/python/site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/kirillviksman/Library/Python/3.14/lib/python/site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Collecting contourpy>=1.0.1 (from matplotlib->catboost)
  Downloading contourpy-1.3.3-cp314-cp314-macosx_10_13_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib->catboost)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->catboost)
  Downloading fonttools-4.62.1-cp314-cp314-macosx_10_15_x86_64.whl.metadata (117 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->catboost)
  Downloading kiwisolver-1.5.0-cp314-cp314-macosx_10_15_x86_64.whl.metadata (5.1 kB)
Requirement already satisfied: packaging>=20.0 in /Users/kirillviksman/Library/Python/3.14/lib/python/site-packages (from matplotlib->catboost) (25.0)
Collecting pillow>=8 (from matplotlib->catboost)
  Downloading pillow-12.2.0-cp314-cp314-macosx_10_15_x86_64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib->catboost)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Collecting narwhals>=1.15.1 (from plotly->catboost)
  Downloading narwhals-2.19.0-py3-none-any.whl.metadata (14 kB)
Downloading lightgbm-4.6.0-py3-none-macosx_10_15_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 2.3 MB/s  0:00:00 eta 0:00:01
Downloading xgboost-3.2.0-py3-none-macosx_10_15_x86_64.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 2.9 MB/s  0:00:00 eta 0:00:01
Downloading catboost-1.2.10-cp314-cp314-macosx_11_0_universal2.whl (28.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.8/28.8 MB 3.4 MB/s  0:00:08m0:00:0100:01
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Downloading matplotlib-3.10.8-cp314-cp314-macosx_10_13_x86_64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 6.1 MB/s  0:00:01 eta 0:00:01
Downloading contourpy-1.3.3-cp314-cp314-macosx_10_13_x86_64.whl (292 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.62.1-cp314-cp314-macosx_10_15_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 4.0 MB/s  0:00:00 eta 0:00:01
Downloading kiwisolver-1.5.0-cp314-cp314-macosx_10_15_x86_64.whl (66 kB)
Downloading pillow-12.2.0-cp314-cp314-macosx_10_15_x86_64.whl (5.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 2.3 MB/s  0:00:02m0:00:0100:01
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Downloading plotly-6.7.0-py3-none-any.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 5.2 MB/s  0:00:01m0:00:0100:01
Downloading narwhals-2.19.0-py3-none-any.whl (446 kB)
Installing collected packages: pyparsing, pillow, narwhals, kiwisolver, graphviz, fonttools, cycler, contourpy, xgboost, plotly, matplotlib, lightgbm, catboost
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/13 [catboost]/13 [catboost]b]
Successfully installed catboost-1.2.10 contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 graphviz-0.21 kiwisolver-1.5.0 lightgbm-4.6.0 matplotlib-3.10.8 narwhals-2.19.0 pillow-12.2.0 plotly-6.7.0 pyparsing-3.3.2 xgboost-3.2.0

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from sklearn.model_selection import train_test_split
import json
import warnings
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_log_error, roc_auc_score
from sklearn.model_selection import ParameterSampler, train_test_split
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import (
    RandomForestRegressor,
    RandomForestClassifier,
    HistGradientBoostingRegressor,
    HistGradientBoostingClassifier,
)

import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostRegressor, CatBoostClassifier

warnings.filterwarnings("ignore")
pd.options.display.max_rows = 1000

dataset = pd.read_csv(f"1_{NAME}.csv")

if dataset.columns[0].startswith("Unnamed"):
    dataset = dataset.drop(columns=dataset.columns[0])

dataset = dataset.reset_index(drop=True)

SHAPE = dataset.shape

train_mask = dataset["dtype"] == "train"
test_mask = dataset["dtype"] == "test"

train_all = dataset.loc[train_mask].copy().reset_index(drop=True)
test = dataset.loc[test_mask].copy().reset_index(drop=True)

print("dataset:", dataset.shape)
print("train:", train_all.shape)
print("test:", test.shape)


# Feature block
target_cols = ["__price", "__churn", "dtype"]
object_cols = dataset.select_dtypes(include=["object"]).columns.tolist()

feature_cols_all = [
    c for c in dataset.columns
    if c not in target_cols and c not in object_cols
]

X_numeric = dataset[feature_cols_all].replace([np.inf, -np.inf], np.nan)
train_numeric = X_numeric.loc[train_mask].copy().reset_index(drop=True)
test_numeric = X_numeric.loc[test_mask].copy().reset_index(drop=True)

print("numeric features:", len(feature_cols_all))


# OOT split for price
if "timestamp" in train_all.columns:
    train_all["timestamp_dt"] = pd.to_datetime(train_all["timestamp"])
    train_sorted = train_all.sort_values("timestamp_dt").reset_index(drop=True)

    oot_cutoff = train_sorted["timestamp_dt"].quantile(0.80)

    dev_mask_price = train_sorted["timestamp_dt"] < oot_cutoff
    oot_mask_price = train_sorted["timestamp_dt"] >= oot_cutoff
else:
    split_pos = int(len(train_all) * 0.8)
    train_sorted = train_all.copy().reset_index(drop=True)
    dev_mask_price = np.arange(len(train_sorted)) < split_pos
    oot_mask_price = np.arange(len(train_sorted)) >= split_pos

train_numeric_reset = train_numeric.reset_index(drop=True)
train_numeric_sorted = train_numeric_reset.loc[train_sorted.index].reset_index(drop=True)

X_dev_full = train_numeric_sorted.loc[dev_mask_price].reset_index(drop=True)
X_oot_full = train_numeric_sorted.loc[oot_mask_price].reset_index(drop=True)

y_price_dev = train_sorted.loc[dev_mask_price, "__price"].reset_index(drop=True)
y_price_oot = train_sorted.loc[oot_mask_price, "__price"].reset_index(drop=True)

print("price dev:", X_dev_full.shape, "price oot:", X_oot_full.shape)

# Separate split for churn
train_all_reset = train_all.reset_index(drop=True)
train_numeric_reset = train_numeric.reset_index(drop=True)

X_churn_source = train_numeric_reset.copy()
y_churn_source = train_all_reset["__churn"].astype(int).copy()

X_churn_dev_full, X_churn_oot_full, y_churn_dev, y_churn_oot = train_test_split(
    X_churn_source,
    y_churn_source,
    test_size=0.20,
    random_state=47,
    stratify=y_churn_source
)

X_churn_dev_full = X_churn_dev_full.reset_index(drop=True)
X_churn_oot_full = X_churn_oot_full.reset_index(drop=True)
y_churn_dev = y_churn_dev.reset_index(drop=True)
y_churn_oot = y_churn_oot.reset_index(drop=True)

print("churn dev:", X_churn_dev_full.shape, "churn oot:", X_churn_oot_full.shape)


# Raw metrics for model selection
def metric_for_price_raw(y_true, y_pred):
    y_pred = np.clip(np.asarray(y_pred), 1e-9, None)
    return -mean_squared_log_error(y_true=y_true, y_pred=y_pred)

def metric_for_churn_raw(y_true, y_score):
    return roc_auc_score(y_true=y_true, y_score=y_score)


# Feature preselection helper

def select_top_model_features(X_dev, y_dev, task="regression", top_k=150):
    imputer = SimpleImputer(strategy="median")

    X_dev_imp = pd.DataFrame(
        imputer.fit_transform(X_dev),
        index=X_dev.index,
        columns=X_dev.columns
    )

    if task == "regression":
        selector = lgb.LGBMRegressor(
            n_estimators=200,
            learning_rate=0.05,
            num_leaves=31,
            random_state=47,
            n_jobs=-1,
            verbosity=-1
        )
        selector.fit(X_dev_imp, y_dev)
    else:
        selector = lgb.LGBMClassifier(
            n_estimators=200,
            learning_rate=0.05,
            num_leaves=31,
            random_state=47,
            n_jobs=-1,
            verbosity=-1
        )
        selector.fit(X_dev_imp, y_dev)

    imp = pd.Series(selector.feature_importances_, index=X_dev_imp.columns).sort_values(ascending=False)

    selected = imp[imp > 0].index.tolist()
    if len(selected) > top_k:
        selected = selected[:top_k]
    if len(selected) < min(top_k, len(imp)):
        selected = imp.head(top_k).index.tolist()

    return selected

price_features = select_top_model_features(
    X_dev_full, y_price_dev,
    task="regression",
    top_k=160
)

churn_features = select_top_model_features(
    X_churn_dev_full, y_churn_dev,
    task="classification",
    top_k=180
)

print("price_features:", len(price_features))
print("churn_features:", len(churn_features))


# Final imputers

price_imputer = SimpleImputer(strategy="median")
X_price_dev = price_imputer.fit_transform(X_dev_full[price_features]).astype("float32")
X_price_oot = price_imputer.transform(X_oot_full[price_features]).astype("float32")

churn_imputer = SimpleImputer(strategy="median")
X_churn_dev = churn_imputer.fit_transform(X_churn_dev_full[churn_features]).astype("float32")
X_churn_oot = churn_imputer.transform(X_churn_oot_full[churn_features]).astype("float32")


# Random seed for search

rng = 42

def build_price_model(alg, params):
    if alg == "Decision Tree":
        return DecisionTreeRegressor(random_state=47, **params)

    if alg == "Random Forest":
        return RandomForestRegressor(random_state=47, n_jobs=-1, **params)

    if alg == "Hist Gradient Boosting":
        return HistGradientBoostingRegressor(
            random_state=47,
            early_stopping=True,
            validation_fraction=0.1,
            n_iter_no_change=20,
            **params
        )

    if alg == "LightGBM":
        return lgb.LGBMRegressor(
            random_state=47,
            objective="regression",
            n_jobs=-1,
            verbosity=-1,
            **params
        )

    if alg == "XGBoost":
        return xgb.XGBRegressor(
            random_state=47,
            objective="reg:squarederror",
            tree_method="hist",
            n_jobs=-1,
            eval_metric="rmse",
            **params
        )

    if alg == "CatBoost":
        return CatBoostRegressor(
            random_seed=47,
            loss_function="RMSE",
            verbose=False,
            **params
        )

    raise ValueError(f"Unknown algorithm: {alg}")

def build_churn_model(alg, params):
    if alg == "Decision Tree":
        return DecisionTreeClassifier(random_state=47, **params)

    if alg == "Random Forest":
        return RandomForestClassifier(random_state=47, n_jobs=-1, **params)

    if alg == "Hist Gradient Boosting":
        return HistGradientBoostingClassifier(
            random_state=47,
            early_stopping=True,
            validation_fraction=0.1,
            n_iter_no_change=20,
            **params
        )

    if alg == "LightGBM":
        return lgb.LGBMClassifier(
            random_state=47,
            objective="binary",
            n_jobs=-1,
            verbosity=-1,
            **params
        )

    if alg == "XGBoost":
        return xgb.XGBClassifier(
            random_state=47,
            objective="binary:logistic",
            tree_method="hist",
            n_jobs=-1,
            eval_metric="auc",
            **params
        )

    if alg == "CatBoost":
        return CatBoostClassifier(
            random_seed=47,
            loss_function="Logloss",
            eval_metric="AUC",
            verbose=False,
            **params
        )

    raise ValueError(f"Unknown algorithm: {alg}")

def fit_price_model(model, alg, X_dev, y_dev, X_oot, y_oot):
    if alg == "LightGBM":
        model.fit(
            X_dev, y_dev,
            eval_set=[(X_oot, y_oot)],
            callbacks=[lgb.early_stopping(30, verbose=False)]
        )
    elif alg == "CatBoost":
        model.fit(
            X_dev, y_dev,
            eval_set=(X_oot, y_oot),
            use_best_model=True,
            verbose=False
        )
    else:
        model.fit(X_dev, y_dev)
    return model

def fit_churn_model(model, alg, X_dev, y_dev, X_oot, y_oot):
    if alg == "LightGBM":
        model.fit(
            X_dev, y_dev,
            eval_set=[(X_oot, y_oot)],
            callbacks=[lgb.early_stopping(30, verbose=False)]
        )
    elif alg == "CatBoost":
        model.fit(
            X_dev, y_dev,
            eval_set=(X_oot, y_oot),
            use_best_model=True,
            verbose=False
        )
    else:
        model.fit(X_dev, y_dev)
    return model

dataset: (30471, 399)
train: (20483, 399)
test: (9988, 399)
numeric features: 376
price dev: (16368, 376) price oot: (4115, 376)
churn dev: (16386, 376) churn oot: (4097, 376)
price_features: 160
churn_features: 180

In [ ]:
rng = 42
n_experiments = 11  

price_spaces = {
    "Decision Tree": {
        "max_depth": [4, 6, 8, 10, 12, None],
        "min_samples_leaf": [5, 10, 20, 40, 80],
        "min_samples_split": [10, 20, 50, 100, 200],
        "criterion": ["squared_error", "friedman_mse"],
    },

    "Random Forest": {
        "n_estimators": [80, 120, 160],
        "max_depth": [8, 12, 16, 20, None],
        "min_samples_leaf": [1, 2, 5, 10],
        "max_features": ["sqrt", 0.5, 0.8],
    },

    "Hist Gradient Boosting": {
        "learning_rate": [0.03, 0.05, 0.08],
        "max_iter": [150, 220, 300],
        "max_depth": [4, 6, 8, None],
        "min_samples_leaf": [10, 20, 40, 80],
        "l2_regularization": [0.0, 1.0, 3.0, 5.0],
        "max_leaf_nodes": [15, 31, 63],
    },

    "LightGBM": {
        "learning_rate": [0.03, 0.05, 0.08],
        "n_estimators": [200, 320, 450],
        "num_leaves": [31, 63, 127],
        "min_child_samples": [10, 20, 40, 80],
        "subsample": [0.7, 0.85, 1.0],
        "colsample_bytree": [0.6, 0.8, 1.0],
        "reg_lambda": [0.0, 1.0, 3.0, 5.0],
    },

    "XGBoost": {
        "learning_rate": [0.03, 0.05, 0.08],
        "n_estimators": [200, 320, 450],
        "max_depth": [4, 6, 8],
        "min_child_weight": [1, 3, 5],
        "subsample": [0.7, 0.85, 1.0],
        "colsample_bytree": [0.6, 0.8, 1.0],
        "reg_lambda": [1.0, 3.0, 5.0, 10.0],
        "gamma": [0.0, 0.1, 0.3],
    },

    "CatBoost": {
        "learning_rate": [0.03, 0.05, 0.08],
        "iterations": [200, 320, 450],
        "depth": [4, 6, 8, 10],
        "l2_leaf_reg": [1, 3, 5, 7, 10],
        "bagging_temperature": [0.0, 0.5, 1.0],
        "random_strength": [0.5, 1.0, 2.0],
    },
}

scoring_price_rows = []
best_price = None

for alg, space in price_spaces.items():
    sampled_params = list(ParameterSampler(space, n_iter=n_experiments, random_state=rng))

    for params in sampled_params:
        model = build_price_model(alg, params)
        model = fit_price_model(model, alg, X_price_dev, y_price_dev, X_price_oot, y_price_oot)

        pred_dev = model.predict(X_price_dev)
        pred_oot = model.predict(X_price_oot)

        score_train = metric_for_price(y_price_dev, np.clip(pred_dev, 1e-9, None))
        score_test = metric_for_price(y_price_oot, np.clip(pred_oot, 1e-9, None))

        row = {
            "alg": alg,
            "hyperparametes": json.dumps(params, sort_keys=True),
            "metric_name": "metric_for_price",
            "score_train": score_train,
            "score_test": score_test,
        }
        scoring_price_rows.append(row)

        raw_test = metric_for_price_raw(y_price_oot, pred_oot)

        if (best_price is None) or (raw_test > best_price["raw_score_test"]):
            best_price = {
                "alg": alg,
                "params": params,
                "raw_score_test": raw_test,
                "score_train": score_train,
                "score_test": score_test,
            }

scoring_price = pd.DataFrame(scoring_price_rows).sort_values(
    ["score_test", "score_train"],
    ascending=False
).reset_index(drop=True)

print("BEST REGRESSION MODEL")
print(best_price["alg"])
print(best_price["params"])
print("train:", best_price["score_train"], "test:", best_price["score_test"])

scoring_price.head(20)

BEST REGRESSION MODEL
LightGBM
{'subsample': 1.0, 'reg_lambda': 3.0, 'num_leaves': 127, 'n_estimators': 450, 'min_child_samples': 80, 'learning_rate': 0.05, 'colsample_bytree': 0.6}
train: -0.243 test: -0.245

,alg,hyperparametes,metric_name,score_train,score_test
0,LightGBM,"{""colsample_bytree"": 0.6, ""learning_rate"": 0.0...",metric_for_price,-0.241,-0.245
1,LightGBM,"{""colsample_bytree"": 0.6, ""learning_rate"": 0.0...",metric_for_price,-0.242,-0.245
2,LightGBM,"{""colsample_bytree"": 0.6, ""learning_rate"": 0.0...",metric_for_price,-0.242,-0.245
3,LightGBM,"{""colsample_bytree"": 0.6, ""learning_rate"": 0.0...",metric_for_price,-0.242,-0.245
4,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.243,-0.245
5,LightGBM,"{""colsample_bytree"": 0.6, ""learning_rate"": 0.0...",metric_for_price,-0.243,-0.245
6,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.243,-0.245
7,Hist Gradient Boosting,"{""l2_regularization"": 0.0, ""learning_rate"": 0....",metric_for_price,-0.244,-0.245
8,Hist Gradient Boosting,"{""l2_regularization"": 1.0, ""learning_rate"": 0....",metric_for_price,-0.244,-0.245
9,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.244,-0.245
10,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.244,-0.245
11,LightGBM,"{""colsample_bytree"": 0.8, ""learning_rate"": 0.0...",metric_for_price,-0.245,-0.245
12,LightGBM,"{""colsample_bytree"": 0.8, ""learning_rate"": 0.0...",metric_for_price,-0.245,-0.245
13,CatBoost,"{""bagging_temperature"": 0.5, ""depth"": 8, ""iter...",metric_for_price,-0.245,-0.245
14,CatBoost,"{""bagging_temperature"": 1.0, ""depth"": 4, ""iter...",metric_for_price,-0.245,-0.245
15,CatBoost,"{""bagging_temperature"": 0.0, ""depth"": 10, ""ite...",metric_for_price,-0.245,-0.245
16,CatBoost,"{""bagging_temperature"": 1.0, ""depth"": 4, ""iter...",metric_for_price,-0.246,-0.245
17,CatBoost,"{""bagging_temperature"": 1.0, ""depth"": 8, ""iter...",metric_for_price,-0.246,-0.245
18,CatBoost,"{""bagging_temperature"": 1.0, ""depth"": 6, ""iter...",metric_for_price,-0.246,-0.245
19,CatBoost,"{""bagging_temperature"": 1.0, ""depth"": 4, ""iter...",metric_for_price,-0.246,-0.245

In [8]:
pos_ratio = (1 - y_churn_dev.mean()) / max(y_churn_dev.mean(), 1e-9)

churn_spaces = {
    "Decision Tree": {
        "max_depth": [3, 4, 5, 6, 8],
        "min_samples_leaf": [20, 40, 80, 120],
        "min_samples_split": [50, 100, 200],
        "criterion": ["gini", "entropy", "log_loss"],
        "class_weight": [None, "balanced"],
    },

    "Random Forest": {
        "n_estimators": [120, 180, 240],
        "max_depth": [4, 6, 8, 10, 12],
        "min_samples_leaf": [5, 10, 20, 40],
        "max_features": ["sqrt", 0.5, 0.7],
        "class_weight": [None, "balanced", "balanced_subsample"],
    },

    "Hist Gradient Boosting": {
        "learning_rate": [0.02, 0.03, 0.05],
        "max_iter": [120, 180, 250],
        "max_depth": [3, 4, 5, 6],
        "min_samples_leaf": [20, 40, 80, 120],
        "l2_regularization": [1.0, 3.0, 5.0, 10.0],
        "max_leaf_nodes": [15, 31],
    },

    "LightGBM": {
        "learning_rate": [0.02, 0.03, 0.05],
        "n_estimators": [150, 220, 320],
        "num_leaves": [15, 31, 63],
        "min_child_samples": [40, 80, 120],
        "subsample": [0.7, 0.85, 1.0],
        "colsample_bytree": [0.6, 0.8, 1.0],
        "reg_lambda": [1.0, 3.0, 5.0, 10.0],
        "class_weight": [None, "balanced"],
    },

    "XGBoost": {
        "learning_rate": [0.02, 0.03, 0.05],
        "n_estimators": [150, 220, 320],
        "max_depth": [3, 4, 5, 6],
        "min_child_weight": [3, 5, 8, 12],
        "subsample": [0.7, 0.85, 1.0],
        "colsample_bytree": [0.6, 0.8, 1.0],
        "reg_lambda": [3.0, 5.0, 10.0, 20.0],
        "gamma": [0.0, 0.2, 0.5],
        "scale_pos_weight": [1.0, float(np.sqrt(pos_ratio)), float(pos_ratio)],
    },

    "CatBoost": {
        "learning_rate": [0.02, 0.03, 0.05],
        "iterations": [150, 220, 320],
        "depth": [3, 4, 5, 6],
        "l2_leaf_reg": [3, 5, 7, 10, 15],
        "bagging_temperature": [0.0, 0.5, 1.0],
        "random_strength": [1.0, 2.0, 5.0],
        "auto_class_weights": [None, "Balanced"],
    },
}

scoring_churn_rows = []
best_churn = None
top_churn_models = []

for alg, space in churn_spaces.items():
    sampled_params = list(ParameterSampler(space, n_iter=n_experiments, random_state=rng))

    for params in sampled_params:
        model = build_churn_model(alg, params)
        model = fit_churn_model(model, alg, X_churn_dev, y_churn_dev, X_churn_oot, y_churn_oot)

        prob_dev = model.predict_proba(X_churn_dev)[:, 1]
        prob_oot = model.predict_proba(X_churn_oot)[:, 1]

        score_train = metric_for_churn(y_churn_dev, prob_dev)
        score_test = metric_for_churn(y_churn_oot, prob_oot)

        row = {
            "alg": alg,
            "hyperparametes": json.dumps(params, sort_keys=True),
            "metric_name": "metric_for_churn",
            "score_train": score_train,
            "score_test": score_test,
        }
        scoring_churn_rows.append(row)

        raw_test = metric_for_churn_raw(y_churn_oot, prob_oot)

        top_churn_models.append({
            "alg": alg,
            "params": params,
            "raw_score_test": raw_test,
            "score_train": score_train,
            "score_test": score_test,
            "model": model,
            "prob_oot": prob_oot
        })

        if (best_churn is None) or (raw_test > best_churn["raw_score_test"]):
            best_churn = {
                "alg": alg,
                "params": params,
                "raw_score_test": raw_test,
                "score_train": score_train,
                "score_test": score_test,
            }

scoring_churn = pd.DataFrame(scoring_churn_rows).sort_values(
    ["score_test", "score_train"],
    ascending=False
).reset_index(drop=True)

print("BEST CLASSIFICATION MODEL")
print(best_churn["alg"])
print(best_churn["params"])
print("train:", best_churn["score_train"], "test:", best_churn["score_test"])

scoring_churn.head(20)

BEST CLASSIFICATION MODEL
LightGBM
{'subsample': 0.85, 'reg_lambda': 3.0, 'num_leaves': 63, 'n_estimators': 320, 'min_child_samples': 80, 'learning_rate': 0.05, 'colsample_bytree': 0.6, 'class_weight': 'balanced'}
train: 1.0 test: 0.989

,alg,hyperparametes,metric_name,score_train,score_test
0,LightGBM,"{""class_weight"": null, ""colsample_bytree"": 0.6...",metric_for_churn,1.000,0.989
1,LightGBM,"{""class_weight"": ""balanced"", ""colsample_bytree...",metric_for_churn,1.000,0.989
2,LightGBM,"{""class_weight"": ""balanced"", ""colsample_bytree...",metric_for_churn,1.000,0.988
3,LightGBM,"{""class_weight"": ""balanced"", ""colsample_bytree...",metric_for_churn,1.000,0.987
4,LightGBM,"{""class_weight"": ""balanced"", ""colsample_bytree...",metric_for_churn,0.999,0.986
5,Hist Gradient Boosting,"{""l2_regularization"": 5.0, ""learning_rate"": 0....",metric_for_churn,0.997,0.983
6,Random Forest,"{""class_weight"": ""balanced_subsample"", ""max_de...",metric_for_churn,0.995,0.980
7,Hist Gradient Boosting,"{""l2_regularization"": 10.0, ""learning_rate"": 0...",metric_for_churn,0.993,0.980
8,LightGBM,"{""class_weight"": ""balanced"", ""colsample_bytree...",metric_for_churn,0.995,0.979
9,LightGBM,"{""class_weight"": null, ""colsample_bytree"": 0.6...",metric_for_churn,0.994,0.979
10,Hist Gradient Boosting,"{""l2_regularization"": 10.0, ""learning_rate"": 0...",metric_for_churn,0.991,0.978
11,Random Forest,"{""class_weight"": ""balanced_subsample"", ""max_de...",metric_for_churn,0.994,0.977
12,Hist Gradient Boosting,"{""l2_regularization"": 10.0, ""learning_rate"": 0...",metric_for_churn,0.989,0.977
13,XGBoost,"{""colsample_bytree"": 1.0, ""gamma"": 0.5, ""learn...",metric_for_churn,0.989,0.976
14,CatBoost,"{""auto_class_weights"": ""Balanced"", ""bagging_te...",metric_for_churn,0.989,0.976
15,LightGBM,"{""class_weight"": ""balanced"", ""colsample_bytree...",metric_for_churn,0.988,0.975
16,XGBoost,"{""colsample_bytree"": 0.8, ""gamma"": 0.0, ""learn...",metric_for_churn,0.988,0.975
17,LightGBM,"{""class_weight"": ""balanced"", ""colsample_bytree...",metric_for_churn,0.987,0.975
18,LightGBM,"{""class_weight"": ""balanced"", ""colsample_bytree...",metric_for_churn,0.987,0.975
19,XGBoost,"{""colsample_bytree"": 1.0, ""gamma"": 0.2, ""learn...",metric_for_churn,0.987,0.975

In [ ]:
########


#  local fine-tuning around the best LightGBM for __price

from sklearn.model_selection import ParameterSampler
import json
import pandas as pd
import numpy as np

# backup current best result
best_price_before_tuning = dict(best_price)

# local search  around the best LightGBM region
local_lgb_space = {
    "learning_rate": [0.04, 0.05, 0.06, 0.07, 0.08, 0.10],
    "n_estimators": [300, 380, 450, 520, 650, 800],
    "num_leaves": [95, 111, 127, 143, 160],
    "min_child_samples": [20, 30, 40, 50, 60, 80],
    "subsample": [0.80, 0.85, 0.90, 1.00],
    "colsample_bytree": [0.80, 0.90, 1.00],
    "reg_lambda": [0.5, 1.0, 2.0, 3.0, 5.0],
}

n_local_experiments = 60
local_rows = []
best_price_local = None

sampled_params = list(
    ParameterSampler(local_lgb_space, n_iter=n_local_experiments, random_state=123)
)

print(f"Running local LightGBM fine-tuning: {n_local_experiments} experiments")

for params in sampled_params:
    model = build_price_model("LightGBM", params)
    model = fit_price_model(model, "LightGBM", X_price_dev, y_price_dev, X_price_oot, y_price_oot)

    pred_dev = model.predict(X_price_dev)
    pred_oot = model.predict(X_price_oot)

    pred_dev = np.clip(pred_dev, 1e-9, None)
    pred_oot = np.clip(pred_oot, 1e-9, None)

    score_train = metric_for_price(y_price_dev, pred_dev)
    score_test = metric_for_price(y_price_oot, pred_oot)
    raw_test = metric_for_price_raw(y_price_oot, pred_oot)

    row = {
        "alg": "LightGBM_local_tuning",
        "hyperparametes": json.dumps(params, sort_keys=True),
        "metric_name": "metric_for_price",
        "score_train": score_train,
        "score_test": score_test,
        "raw_score_test": raw_test,
    }
    local_rows.append(row)

    if (best_price_local is None) or (raw_test > best_price_local["raw_score_test"]):
        best_price_local = {
            "alg": "LightGBM",
            "params": params,
            "raw_score_test": raw_test,
            "score_train": score_train,
            "score_test": score_test,
        }

scoring_price_local = pd.DataFrame(local_rows).sort_values(
    ["raw_score_test", "score_train"],
    ascending=False
).reset_index(drop=True)

print("\nCurrent best price model BEFORE local tuning:")
print(best_price_before_tuning["alg"])
print(best_price_before_tuning["params"])
print("train:", best_price_before_tuning["score_train"], "test:", best_price_before_tuning["score_test"])

print("\nBest local LightGBM:")
print(best_price_local["alg"])
print(best_price_local["params"])
print("train:", best_price_local["score_train"], "test:", best_price_local["score_test"])

if best_price_local["raw_score_test"] > best_price_before_tuning["raw_score_test"]:
    print("\nLocal tuning improved the result. Updating best_price.")
    best_price = dict(best_price_local)
else:
    print("\nNo improvement. Keeping the old best_price.")
    best_price = dict(best_price_before_tuning)

display(scoring_price_local.head(20))

Running local LightGBM fine-tuning: 60 experiments

Current best price model BEFORE local tuning:
LightGBM
{'subsample': 1.0, 'reg_lambda': 3.0, 'num_leaves': 127, 'n_estimators': 450, 'min_child_samples': 80, 'learning_rate': 0.05, 'colsample_bytree': 0.6}
train: -0.243 test: -0.245

Best local LightGBM:
LightGBM
{'subsample': 1.0, 'reg_lambda': 3.0, 'num_leaves': 127, 'n_estimators': 450, 'min_child_samples': 40, 'learning_rate': 0.06, 'colsample_bytree': 0.9}
train: -0.238 test: -0.245

Local tuning improved the result. Updating best_price.

,alg,hyperparametes,metric_name,score_train,score_test,raw_score_test
0,LightGBM_local_tuning,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.238,-0.245,-0.244676
1,LightGBM_local_tuning,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.245,-0.244705
2,LightGBM_local_tuning,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.238,-0.245,-0.244712
3,LightGBM_local_tuning,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.241,-0.245,-0.244744
4,LightGBM_local_tuning,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.242,-0.245,-0.244775
5,LightGBM_local_tuning,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.238,-0.245,-0.244778
6,LightGBM_local_tuning,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.244,-0.245,-0.244871
7,LightGBM_local_tuning,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.239,-0.245,-0.244880
8,LightGBM_local_tuning,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.1...",metric_for_price,-0.242,-0.245,-0.244887
9,LightGBM_local_tuning,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.243,-0.245,-0.244898
10,LightGBM_local_tuning,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.243,-0.245,-0.244922
11,LightGBM_local_tuning,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.244,-0.245,-0.244928
12,LightGBM_local_tuning,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.244,-0.245,-0.244956
13,LightGBM_local_tuning,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.245,-0.244961
14,LightGBM_local_tuning,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.244,-0.245,-0.244964
15,LightGBM_local_tuning,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.1...",metric_for_price,-0.243,-0.245,-0.244972
16,LightGBM_local_tuning,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.1...",metric_for_price,-0.240,-0.245,-0.244983
17,LightGBM_local_tuning,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.244,-0.245,-0.244990
18,LightGBM_local_tuning,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.245,-0.245,-0.244991
19,LightGBM_local_tuning,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.243,-0.245,-0.244992

In [ ]:
#########
# local tuning around the new best LightGBM for __price

import json
import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import ParameterSampler

best_price_before_ultra = dict(best_price)

ultra_lgb_space = {
    "learning_rate": [0.05, 0.06, 0.07],
    "n_estimators": [650, 800, 950, 1100],
    "num_leaves": [95, 111, 127],
    "min_child_samples": [40, 50, 60],
    "subsample": [0.85, 0.90, 0.95, 1.00],
    "colsample_bytree": [0.90, 1.00],
    "reg_lambda": [2.0, 3.0, 4.0, 5.0],
    "seed": [17, 47, 77, 101, 123],
}

n_ultra_experiments = 40
ultra_rows = []
best_price_ultra = None

sampled_params = list(
    ParameterSampler(ultra_lgb_space, n_iter=n_ultra_experiments, random_state=321)
)

print(f"Running ultra-local LightGBM tuning: {n_ultra_experiments} experiments")

for params in sampled_params:
    seed = params["seed"]
    model_params = {k: v for k, v in params.items() if k != "seed"}

    model = lgb.LGBMRegressor(
        random_state=seed,
        objective="regression",
        n_jobs=-1,
        verbosity=-1,
        **model_params
    )

    model.fit(
        X_price_dev, y_price_dev,
        eval_set=[(X_price_oot, y_price_oot)],
        callbacks=[lgb.early_stopping(30, verbose=False)]
    )

    pred_dev = np.clip(model.predict(X_price_dev), 1e-9, None)
    pred_oot = np.clip(model.predict(X_price_oot), 1e-9, None)

    score_train = metric_for_price(y_price_dev, pred_dev)
    score_test = metric_for_price(y_price_oot, pred_oot)
    raw_test = metric_for_price_raw(y_price_oot, pred_oot)

    row = {
        "alg": "LightGBM_ultra_local",
        "hyperparametes": json.dumps(params, sort_keys=True),
        "metric_name": "metric_for_price",
        "score_train": score_train,
        "score_test": score_test,
        "raw_score_test": raw_test,
    }
    ultra_rows.append(row)

    if (best_price_ultra is None) or (raw_test > best_price_ultra["raw_score_test"]):
        best_price_ultra = {
            "alg": "LightGBM",
            "params": model_params,
            "seed": seed,
            "raw_score_test": raw_test,
            "score_train": score_train,
            "score_test": score_test,
        }

scoring_price_ultra = pd.DataFrame(ultra_rows).sort_values(
    ["raw_score_test", "score_train"],
    ascending=False
).reset_index(drop=True)

print("\nCurrent best before ultra-local tuning:")
print(best_price_before_ultra["alg"])
print(best_price_before_ultra["params"])
print("train:", best_price_before_ultra["score_train"], "test:", best_price_before_ultra["score_test"])

print("\nBest ultra-local LightGBM:")
print(best_price_ultra["alg"])
print(best_price_ultra["params"])
print("seed:", best_price_ultra["seed"])
print("train:", best_price_ultra["score_train"], "test:", best_price_ultra["score_test"])
print("raw_score_test:", best_price_ultra["raw_score_test"])

if best_price_ultra["raw_score_test"] > best_price_before_ultra["raw_score_test"]:
    print("\nUltra-local tuning improved the result. Updating best_price.")
    best_price = {
        "alg": best_price_ultra["alg"],
        "params": best_price_ultra["params"],
        "raw_score_test": best_price_ultra["raw_score_test"],
        "score_train": best_price_ultra["score_train"],
        "score_test": best_price_ultra["score_test"],
    }
else:
    print("\nNo improvement. Keeping the old best_price.")
    best_price = dict(best_price_before_ultra)

display(scoring_price_ultra.head(20))

Running ultra-local LightGBM tuning: 40 experiments

Current best before ultra-local tuning:
LightGBM
{'subsample': 1.0, 'reg_lambda': 3.0, 'num_leaves': 127, 'n_estimators': 450, 'min_child_samples': 40, 'learning_rate': 0.06, 'colsample_bytree': 0.9}
train: -0.238 test: -0.245

Best ultra-local LightGBM:
LightGBM
{'subsample': 0.95, 'reg_lambda': 2.0, 'num_leaves': 111, 'n_estimators': 650, 'min_child_samples': 50, 'learning_rate': 0.06, 'colsample_bytree': 1.0}
seed: 101
train: -0.239 test: -0.245
raw_score_test: -0.24452522797559154

Ultra-local tuning improved the result. Updating best_price.

,alg,hyperparametes,metric_name,score_train,score_test,raw_score_test
0,LightGBM_ultra_local,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.239,-0.245,-0.244525
1,LightGBM_ultra_local,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.241,-0.245,-0.244616
2,LightGBM_ultra_local,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.242,-0.245,-0.244678
3,LightGBM_ultra_local,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.239,-0.245,-0.244686
4,LightGBM_ultra_local,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.245,-0.244698
5,LightGBM_ultra_local,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.241,-0.245,-0.244744
6,LightGBM_ultra_local,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.245,-0.244753
7,LightGBM_ultra_local,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.239,-0.245,-0.244777
8,LightGBM_ultra_local,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.239,-0.245,-0.244777
9,LightGBM_ultra_local,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.241,-0.245,-0.244807
10,LightGBM_ultra_local,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.237,-0.245,-0.244811
11,LightGBM_ultra_local,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.239,-0.245,-0.244826
12,LightGBM_ultra_local,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.245,-0.244846
13,LightGBM_ultra_local,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.239,-0.245,-0.244878
14,LightGBM_ultra_local,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.241,-0.245,-0.244880
15,LightGBM_ultra_local,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.242,-0.245,-0.244899
16,LightGBM_ultra_local,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.244,-0.245,-0.244912
17,LightGBM_ultra_local,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.243,-0.245,-0.244928
18,LightGBM_ultra_local,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.245,-0.244934
19,LightGBM_ultra_local,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.241,-0.245,-0.244943

In [ ]:
######

#  local search around the current best LightGBM for __price
import json
import numpy as np
import pandas as pd
import lightgbm as lgb
from sklearn.model_selection import ParameterSampler

best_price_before_dense = dict(best_price)

dense_lgb_space = {
    "learning_rate": [0.045, 0.05, 0.055, 0.06, 0.065, 0.07],
    "n_estimators": [500, 650, 800, 950, 1100, 1300],
    "num_leaves": [95, 103, 111, 119, 127],
    "min_child_samples": [35, 40, 45, 50, 55, 60],
    "subsample": [0.90, 0.95, 1.00],
    "colsample_bytree": [0.90, 0.95, 1.00],
    "reg_lambda": [1.0, 1.5, 2.0, 2.5, 3.0, 4.0],
    "seed": [17, 47, 77, 101, 123, 202],
}

n_dense_experiments = 200
dense_rows = []
best_price_dense = None

sampled_params = list(
    ParameterSampler(dense_lgb_space, n_iter=n_dense_experiments, random_state=999)
)

print(f"Running dense LightGBM search: {n_dense_experiments} experiments")

for params in sampled_params:
    seed = params["seed"]
    model_params = {k: v for k, v in params.items() if k != "seed"}

    model = lgb.LGBMRegressor(
        random_state=seed,
        objective="regression",
        n_jobs=-1,
        verbosity=-1,
        **model_params
    )

    model.fit(
        X_price_dev, y_price_dev,
        eval_set=[(X_price_oot, y_price_oot)],
        callbacks=[lgb.early_stopping(40, verbose=False)]
    )

    pred_dev = np.clip(model.predict(X_price_dev), 1e-9, None)
    pred_oot = np.clip(model.predict(X_price_oot), 1e-9, None)

    score_train = metric_for_price(y_price_dev, pred_dev)
    score_test = metric_for_price(y_price_oot, pred_oot)
    raw_test = metric_for_price_raw(y_price_oot, pred_oot)

    row = {
        "alg": "LightGBM_dense_search",
        "hyperparametes": json.dumps(params, sort_keys=True),
        "metric_name": "metric_for_price",
        "score_train": score_train,
        "score_test": score_test,
        "raw_score_test": raw_test,
    }
    dense_rows.append(row)

    if (best_price_dense is None) or (raw_test > best_price_dense["raw_score_test"]):
        best_price_dense = {
            "alg": "LightGBM",
            "params": model_params,
            "seed": seed,
            "raw_score_test": raw_test,
            "score_train": score_train,
            "score_test": score_test,
        }

scoring_price_dense = pd.DataFrame(dense_rows).sort_values(
    ["raw_score_test", "score_train"],
    ascending=False
).reset_index(drop=True)

print("\nCurrent best before dense search:")
print(best_price_before_dense["alg"])
print(best_price_before_dense["params"])
print("train:", best_price_before_dense["score_train"], "test:", best_price_before_dense["score_test"])
print("raw_score_test:", best_price_before_dense["raw_score_test"])

print("\nBest dense-search LightGBM:")
print(best_price_dense["alg"])
print(best_price_dense["params"])
print("seed:", best_price_dense["seed"])
print("train:", best_price_dense["score_train"], "test:", best_price_dense["score_test"])
print("raw_score_test:", best_price_dense["raw_score_test"])

# update only if truly better
if best_price_dense["raw_score_test"] > best_price_before_dense["raw_score_test"] + 1e-9:
    print("\nDense search improved the result. Updating best_price.")
    best_price = {
        "alg": best_price_dense["alg"],
        "params": best_price_dense["params"],
        "raw_score_test": best_price_dense["raw_score_test"],
        "score_train": best_price_dense["score_train"],
        "score_test": best_price_dense["score_test"],
    }
else:
    print("\nNo improvement. Keeping the old best_price.")
    best_price = dict(best_price_before_dense)

display(scoring_price_dense.head(20))

Running dense LightGBM search: 200 experiments

Current best before dense search:
LightGBM
{'subsample': 0.95, 'reg_lambda': 2.0, 'num_leaves': 111, 'n_estimators': 650, 'min_child_samples': 50, 'learning_rate': 0.06, 'colsample_bytree': 1.0}
train: -0.239 test: -0.245
raw_score_test: -0.24452522797559154

Best dense-search LightGBM:
LightGBM
{'subsample': 0.95, 'reg_lambda': 2.0, 'num_leaves': 127, 'n_estimators': 1300, 'min_child_samples': 50, 'learning_rate': 0.06, 'colsample_bytree': 1.0}
seed: 47
train: -0.237 test: -0.244
raw_score_test: -0.24439342749243928

Dense search improved the result. Updating best_price.

,alg,hyperparametes,metric_name,score_train,score_test,raw_score_test
0,LightGBM_dense_search,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.237,-0.244,-0.244393
1,LightGBM_dense_search,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.236,-0.244,-0.244408
2,LightGBM_dense_search,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.244,-0.244461
3,LightGBM_dense_search,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.245,-0.244504
4,LightGBM_dense_search,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.245,-0.244533
5,LightGBM_dense_search,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.237,-0.245,-0.244537
6,LightGBM_dense_search,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.245,-0.244593
7,LightGBM_dense_search,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.245,-0.244593
8,LightGBM_dense_search,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.245,-0.244603
9,LightGBM_dense_search,"{""colsample_bytree"": 0.95, ""learning_rate"": 0....",metric_for_price,-0.238,-0.245,-0.244618
10,LightGBM_dense_search,"{""colsample_bytree"": 0.95, ""learning_rate"": 0....",metric_for_price,-0.240,-0.245,-0.244625
11,LightGBM_dense_search,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.241,-0.245,-0.244640
12,LightGBM_dense_search,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.241,-0.245,-0.244675
13,LightGBM_dense_search,"{""colsample_bytree"": 0.95, ""learning_rate"": 0....",metric_for_price,-0.240,-0.245,-0.244677
14,LightGBM_dense_search,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.239,-0.245,-0.244683
15,LightGBM_dense_search,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.242,-0.245,-0.244706
16,LightGBM_dense_search,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.245,-0.244734
17,LightGBM_dense_search,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.235,-0.245,-0.244737
18,LightGBM_dense_search,"{""colsample_bytree"": 0.95, ""learning_rate"": 0....",metric_for_price,-0.241,-0.245,-0.244745
19,LightGBM_dense_search,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.239,-0.245,-0.244759

In [ ]:

# large search for ALL 6 regression models (__price)

import json
import numpy as np
import pandas as pd
from sklearn.model_selection import ParameterSampler

best_price_before_all_models = dict(best_price)

print("Current best before large all-model search:")
print(best_price_before_all_models["alg"])
print(best_price_before_all_models["params"])
print("raw_score_test:", best_price_before_all_models["raw_score_test"])

# large number of experiments for EACH regression model
n_experiments_large = 300
rng_large = 5001

price_spaces_large = {
    "Decision Tree": {
        "max_depth": [4, 5, 6, 8, 10, 12, None],
        "min_samples_leaf": [5, 10, 20, 40, 80, 120],
        "min_samples_split": [10, 20, 50, 100, 200],
        "criterion": ["squared_error", "friedman_mse"],
    },

    "Random Forest": {
        "n_estimators": [120, 180, 240, 320, 400],
        "max_depth": [8, 12, 16, 20, None],
        "min_samples_leaf": [1, 2, 5, 10, 20],
        "max_features": ["sqrt", 0.4, 0.5, 0.6, 0.8],
    },

    "Hist Gradient Boosting": {
        "learning_rate": [0.02, 0.03, 0.05, 0.06, 0.08],
        "max_iter": [150, 220, 300, 450, 600],
        "max_depth": [4, 5, 6, 8, None],
        "min_samples_leaf": [10, 20, 40, 80],
        "l2_regularization": [0.0, 0.5, 1.0, 3.0, 5.0, 10.0],
        "max_leaf_nodes": [15, 31, 63],
    },

    "LightGBM": {
        "learning_rate": [0.04, 0.05, 0.055, 0.06, 0.065, 0.07, 0.08],
        "n_estimators": [450, 650, 800, 950, 1100, 1300],
        "num_leaves": [95, 111, 127, 143, 160],
        "min_child_samples": [30, 40, 50, 60, 80],
        "subsample": [0.85, 0.90, 0.95, 1.00],
        "colsample_bytree": [0.90, 0.95, 1.00],
        "reg_lambda": [1.0, 1.25, 1.5, 2.0, 2.5, 3.0, 5.0],
    },

    "XGBoost": {
        "learning_rate": [0.03, 0.04, 0.05, 0.06, 0.08],
        "n_estimators": [400, 600, 800, 1000, 1300],
        "max_depth": [3, 4, 5, 6, 8],
        "min_child_weight": [1, 3, 5, 8, 12],
        "subsample": [0.80, 0.90, 0.95, 1.00],
        "colsample_bytree": [0.80, 0.90, 0.95, 1.00],
        "reg_lambda": [1.0, 2.0, 3.0, 5.0, 10.0],
        "gamma": [0.0, 0.1, 0.2, 0.3, 0.5],
    },

    "CatBoost": {
        "learning_rate": [0.03, 0.04, 0.05, 0.06, 0.08],
        "iterations": [400, 600, 800, 1000, 1300],
        "depth": [4, 5, 6, 8, 10],
        "l2_leaf_reg": [1, 3, 5, 7, 10, 15],
        "bagging_temperature": [0.0, 0.5, 1.0, 2.0],
        "random_strength": [0.5, 1.0, 2.0, 5.0],
    },
}

all_model_rows = []
best_price_all_models = None

for model_idx, (alg, space) in enumerate(price_spaces_large.items(), start=1):
    sampled_params = list(
        ParameterSampler(space, n_iter=n_experiments_large, random_state=rng_large + model_idx)
    )

    print(f"\nRunning {alg}: {n_experiments_large} experiments")

    for i, params in enumerate(sampled_params, start=1):
        model = build_price_model(alg, params)
        model = fit_price_model(model, alg, X_price_dev, y_price_dev, X_price_oot, y_price_oot)

        pred_dev = np.clip(model.predict(X_price_dev), 1e-9, None)
        pred_oot = np.clip(model.predict(X_price_oot), 1e-9, None)

        score_train = metric_for_price(y_price_dev, pred_dev)
        score_test = metric_for_price(y_price_oot, pred_oot)
        raw_test = metric_for_price_raw(y_price_oot, pred_oot)

        row = {
            "alg": alg,
            "hyperparametes": json.dumps(params, sort_keys=True),
            "metric_name": "metric_for_price",
            "score_train": score_train,
            "score_test": score_test,
            "raw_score_test": raw_test,
        }
        all_model_rows.append(row)

        if (best_price_all_models is None) or (raw_test > best_price_all_models["raw_score_test"]):
            best_price_all_models = {
                "alg": alg,
                "params": params,
                "raw_score_test": raw_test,
                "score_train": score_train,
                "score_test": score_test,
            }

        if i % 100 == 0:
            print(
                f"  {alg}: {i}/{n_experiments_large} | "
                f"best raw_score_test so far = {best_price_all_models['raw_score_test']:.9f}"
            )

    pd.DataFrame(all_model_rows).to_csv("scoring_price_all_models_checkpoint.csv", index=False)

scoring_price_all_models_large = pd.DataFrame(all_model_rows).sort_values(
    ["raw_score_test", "score_train"],
    ascending=False
).reset_index(drop=True)

print("\nBest model from large all-model search:")
print(best_price_all_models["alg"])
print(best_price_all_models["params"])
print("train:", best_price_all_models["score_train"], "test:", best_price_all_models["score_test"])
print("raw_score_test:", best_price_all_models["raw_score_test"])

if best_price_all_models["raw_score_test"] > best_price_before_all_models["raw_score_test"] + 1e-9:
    print("\nLarge all-model search improved the result. Updating best_price.")
    best_price = dict(best_price_all_models)
else:
    print("\nNo improvement. Keeping the old best_price.")
    best_price = dict(best_price_before_all_models)

scoring_price_all_models_large.to_csv("scoring_price_all_models_large_final.csv", index=False)
display(scoring_price_all_models_large.head(20))

Current best before large all-model search:
LightGBM
{'subsample': 0.95, 'reg_lambda': 2.0, 'num_leaves': 127, 'n_estimators': 1300, 'min_child_samples': 50, 'learning_rate': 0.06, 'colsample_bytree': 1.0}
raw_score_test: -0.24439342749243928

Running Decision Tree: 300 experiments
  Decision Tree: 100/300 | best raw_score_test so far = -0.246954104
  Decision Tree: 200/300 | best raw_score_test so far = -0.246722649
  Decision Tree: 300/300 | best raw_score_test so far = -0.246722649

Running Random Forest: 300 experiments
  Random Forest: 100/300 | best raw_score_test so far = -0.246011579
  Random Forest: 200/300 | best raw_score_test so far = -0.245692457
  Random Forest: 300/300 | best raw_score_test so far = -0.245692457

Running Hist Gradient Boosting: 300 experiments
  Hist Gradient Boosting: 100/300 | best raw_score_test so far = -0.244931283
  Hist Gradient Boosting: 200/300 | best raw_score_test so far = -0.244921553
  Hist Gradient Boosting: 300/300 | best raw_score_test so far = -0.244921553

Running LightGBM: 300 experiments
  LightGBM: 100/300 | best raw_score_test so far = -0.244472090
  LightGBM: 200/300 | best raw_score_test so far = -0.244425062
  LightGBM: 300/300 | best raw_score_test so far = -0.244425062

Running XGBoost: 300 experiments
  XGBoost: 100/300 | best raw_score_test so far = -0.244425062
  XGBoost: 200/300 | best raw_score_test so far = -0.244425062
  XGBoost: 300/300 | best raw_score_test so far = -0.244425062

Running CatBoost: 300 experiments
  CatBoost: 100/300 | best raw_score_test so far = -0.244425062
  CatBoost: 200/300 | best raw_score_test so far = -0.244425062
  CatBoost: 300/300 | best raw_score_test so far = -0.244425062

Best model from large all-model search:
LightGBM
{'subsample': 1.0, 'reg_lambda': 1.0, 'num_leaves': 127, 'n_estimators': 650, 'min_child_samples': 50, 'learning_rate': 0.055, 'colsample_bytree': 1.0}
train: -0.241 test: -0.244
raw_score_test: -0.24442506241481723

No improvement. Keeping the old best_price.

,alg,hyperparametes,metric_name,score_train,score_test,raw_score_test
0,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.241,-0.244,-0.244425
1,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.244,-0.244430
2,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.239,-0.244,-0.244444
3,LightGBM,"{""colsample_bytree"": 0.95, ""learning_rate"": 0....",metric_for_price,-0.239,-0.244,-0.244472
4,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.241,-0.244,-0.244475
5,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.241,-0.244,-0.244475
6,LightGBM,"{""colsample_bytree"": 0.95, ""learning_rate"": 0....",metric_for_price,-0.236,-0.244,-0.244490
7,LightGBM,"{""colsample_bytree"": 0.95, ""learning_rate"": 0....",metric_for_price,-0.239,-0.244,-0.244494
8,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.238,-0.245,-0.244507
9,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.240,-0.245,-0.244533
10,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.236,-0.245,-0.244551
11,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.239,-0.245,-0.244590
12,LightGBM,"{""colsample_bytree"": 0.9, ""learning_rate"": 0.0...",metric_for_price,-0.239,-0.245,-0.244593
13,LightGBM,"{""colsample_bytree"": 0.95, ""learning_rate"": 0....",metric_for_price,-0.237,-0.245,-0.244597
14,LightGBM,"{""colsample_bytree"": 0.95, ""learning_rate"": 0....",metric_for_price,-0.238,-0.245,-0.244604
15,LightGBM,"{""colsample_bytree"": 0.95, ""learning_rate"": 0....",metric_for_price,-0.241,-0.245,-0.244606
16,LightGBM,"{""colsample_bytree"": 0.95, ""learning_rate"": 0....",metric_for_price,-0.241,-0.245,-0.244606
17,LightGBM,"{""colsample_bytree"": 0.95, ""learning_rate"": 0....",metric_for_price,-0.238,-0.245,-0.244616
18,LightGBM,"{""colsample_bytree"": 0.95, ""learning_rate"": 0....",metric_for_price,-0.241,-0.245,-0.244628
19,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.237,-0.245,-0.244641

In [ ]:



# Refit best regression model on full train using log-target

X_price_train_full = price_imputer.fit_transform(train_numeric[price_features]).astype("float32")
X_price_all_full = price_imputer.transform(X_numeric[price_features]).astype("float32")

y_price_train_full_log = np.log1p(train_all["__price"])

best_regression_model = build_price_model(best_price["alg"], best_price["params"])
best_regression_model = fit_price_model(
    best_regression_model,
    best_price["alg"],
    X_price_train_full,
    y_price_train_full_log,
    X_price_train_full,
    y_price_train_full_log
)

dataset["__price_predict"] = np.expm1(best_regression_model.predict(X_price_all_full))
dataset["__price_predict"] = np.clip(dataset["__price_predict"], 1e-9, None)


X_churn_train_full = churn_imputer.fit_transform(train_numeric[churn_features]).astype("float32")
X_churn_all_full = churn_imputer.transform(X_numeric[churn_features]).astype("float32")

best_classification_model = build_churn_model(best_churn["alg"], best_churn["params"])
best_classification_model = fit_churn_model(
    best_classification_model,
    best_churn["alg"],
    X_churn_train_full,
    train_all["__churn"].astype(int),
    X_churn_train_full,
    train_all["__churn"].astype(int),
)

dataset["__churn_prob"] = best_classification_model.predict_proba(X_churn_all_full)[:, 1]


# refresh train_all and test so that next template cells see new columns
train_all = dataset[dataset["dtype"] == "train"].copy()
test = dataset[dataset["dtype"] == "test"].copy()

print("best regression:", best_price["alg"], best_price["score_test"])
print("best classification:", best_churn["alg"], best_churn["score_test"])

display(scoring_price.head(10))
display(scoring_churn.head(10))
display(dataset[["__price_predict", "__churn_prob"]].head())

best regression: LightGBM -0.244
best classification: LightGBM 0.989

,alg,hyperparametes,metric_name,score_train,score_test
0,LightGBM,"{""colsample_bytree"": 0.6, ""learning_rate"": 0.0...",metric_for_price,-0.241,-0.245
1,LightGBM,"{""colsample_bytree"": 0.6, ""learning_rate"": 0.0...",metric_for_price,-0.242,-0.245
2,LightGBM,"{""colsample_bytree"": 0.6, ""learning_rate"": 0.0...",metric_for_price,-0.242,-0.245
3,LightGBM,"{""colsample_bytree"": 0.6, ""learning_rate"": 0.0...",metric_for_price,-0.242,-0.245
4,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.243,-0.245
5,LightGBM,"{""colsample_bytree"": 0.6, ""learning_rate"": 0.0...",metric_for_price,-0.243,-0.245
6,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.243,-0.245
7,Hist Gradient Boosting,"{""l2_regularization"": 0.0, ""learning_rate"": 0....",metric_for_price,-0.244,-0.245
8,Hist Gradient Boosting,"{""l2_regularization"": 1.0, ""learning_rate"": 0....",metric_for_price,-0.244,-0.245
9,LightGBM,"{""colsample_bytree"": 1.0, ""learning_rate"": 0.0...",metric_for_price,-0.244,-0.245

,alg,hyperparametes,metric_name,score_train,score_test
0,LightGBM,"{""class_weight"": null, ""colsample_bytree"": 0.6...",metric_for_churn,1.000,0.989
1,LightGBM,"{""class_weight"": ""balanced"", ""colsample_bytree...",metric_for_churn,1.000,0.989
2,LightGBM,"{""class_weight"": ""balanced"", ""colsample_bytree...",metric_for_churn,1.000,0.988
3,LightGBM,"{""class_weight"": ""balanced"", ""colsample_bytree...",metric_for_churn,1.000,0.987
4,LightGBM,"{""class_weight"": ""balanced"", ""colsample_bytree...",metric_for_churn,0.999,0.986
5,Hist Gradient Boosting,"{""l2_regularization"": 5.0, ""learning_rate"": 0....",metric_for_churn,0.997,0.983
6,Random Forest,"{""class_weight"": ""balanced_subsample"", ""max_de...",metric_for_churn,0.995,0.980
7,Hist Gradient Boosting,"{""l2_regularization"": 10.0, ""learning_rate"": 0...",metric_for_churn,0.993,0.980
8,LightGBM,"{""class_weight"": ""balanced"", ""colsample_bytree...",metric_for_churn,0.995,0.979
9,LightGBM,"{""class_weight"": null, ""colsample_bytree"": 0.6...",metric_for_churn,0.994,0.979

   __price_predict  __churn_prob
0         5.504451      0.000221
1         7.036023      0.011886
2         3.323380      0.968376
3         4.133183      0.000260
4         6.160621      0.001235

# YOUR WORK IS DONE (Create submission)

In [14]:
metric_for_churn(train_all['__churn'], train_all['__churn_prob'])

1.0

In [15]:
metric_for_price(train_all['__price'], train_all['__price_predict'])

-0.0

In [21]:
def alg1(x):
    """
    Algorithm version 1
    """
    return x['__price_predict']

dataset['__priority'] = dataset.apply(alg1, axis=1)

# YOUR WORK IS DONE (Create submission)

In [17]:
submission = dataset[['__price_predict', '__churn_prob', '__priority']].copy()
submission.to_csv(f'3_{NAME}.csv', index=False)

In [18]:
# this columns must be in dataset
prediction_columns = ['__price_predict', '__churn_prob', '__priority']
submission = dataset[prediction_columns]

if submission.isnull().sum().sum() > 0:
    raise ValueError(f"Submission dataset contained NaN values")

if submission.shape[0] != SHAPE[0]:
    raise ValueError(f'Incorrect submission file shape. Original {SHAPE[0]}. {submission.shape[0]} are given')

# index must be True
output_path = '3_' + NAME + '.csv'

print(f"output file '{output_path}' was created")
# index must be True
submission.to_csv(output_path, index=True)

output file '3_Kirill_Viksman.csv' was created

In [19]:
submission = pd.read_csv(f'3_{NAME}.csv')
if 'Unnamed: 0' in submission.columns:
    submission = submission.drop(columns=['Unnamed: 0'])

submission.to_csv(f'3_{NAME}.csv', index=False)
print('fixed')

fixed

In [20]:
check = pd.read_csv(f'3_{NAME}.csv')
print(check.shape)
print(check.columns.tolist())
print(check.isna().sum())
display(check.head())

(30471, 3)
['__price_predict', '__churn_prob', '__priority']
__price_predict    0
__churn_prob       0
__priority         0
dtype: int64

   __price_predict  __churn_prob  __priority
0         5.504451      0.000221    5.504451
1         7.036023      0.011886    7.036023
2         3.323380      0.968376    3.323380
3         4.133183      0.000260    4.133183
4         6.160621      0.001235    6.160621

проверка результата

In [ ]:
suspicious_cols = [
    c for c in dataset.columns
    if any(word in c.lower() for word in [
        "churn", "target", "label", "prob", "flag", "response", "default", "status"
    ])
]

print("Suspicious columns:")
for c in suspicious_cols:
    print(c)

Suspicious columns:
marital_status
__churn
f_freq_marital_status
f_ohe_marital_status__Married
f_ohe_marital_status__Single

In [ ]:
best_lgbm = build_churn_model(best_churn["alg"], best_churn["params"])
best_lgbm = fit_churn_model(best_lgbm, best_churn["alg"], X_churn_dev, y_churn_dev, X_churn_oot, y_churn_oot)

imp = pd.Series(best_lgbm.feature_importances_, index=churn_features).sort_values(ascending=False)
display(imp.head(30))

f_sem_dep_ratio                      400
total_trans_ct                       370
total_ct_chng_q4_q1                  370
f_sem_rel_per_age                    366
total_revolving_bal                  341
f_sem_change_interaction             327
f_sem_trans_ct_per_month             309
f_int_month_cos_x_trans_amt_m        302
f_int_month_sin_x_trans_amt_m        302
f_sem_change_ratio                   293
f_sem_trans_ct_per_rel               289
credit_limit                         286
avg_utilization_ratio                282
f_int_married_x_family_index         279
f_sem_trans_avg_amount               277
total_trans_amt                      268
total_relationship_count             264
f_int_age_x_floor_ratio              256
f_freq_timestamp                     255
f_sem_revolving_ratio                250
f_sem_trans_amt_per_rel              249
total_amt_chng_q4_q1                 247
f_int_family_index_over_risk         232
f_rs_total_revolving_bal             231
f_sem_trans_amt_per_month            231
f_rs_total_ct_chng_q4_q1             228
avg_open_to_buy                      224
f_sem_inactive_ratio                 208
public_transport_station_min_walk    198
f_sem_floor_ratio                    197
dtype: int32

In [ ]:
from sklearn.model_selection import train_test_split

X_churn_source = train_numeric.reset_index(drop=True).copy()
y_churn_source = train_all["__churn"].astype(int).reset_index(drop=True).copy()

X_dev2, X_oot2, y_dev2, y_oot2 = train_test_split(
    X_churn_source,
    y_churn_source,
    test_size=0.20,
    random_state=99,
    stratify=y_churn_source
)

X_dev2 = X_dev2.reset_index(drop=True)
X_oot2 = X_oot2.reset_index(drop=True)
y_dev2 = y_dev2.reset_index(drop=True)
y_oot2 = y_oot2.reset_index(drop=True)

X_dev2_imp = churn_imputer.fit_transform(X_dev2[churn_features]).astype("float32")
X_oot2_imp = churn_imputer.transform(X_oot2[churn_features]).astype("float32")

model2 = build_churn_model(best_churn["alg"], best_churn["params"])
model2 = fit_churn_model(model2, best_churn["alg"], X_dev2_imp, y_dev2, X_oot2_imp, y_oot2)

prob2 = model2.predict_proba(X_oot2_imp)[:, 1]
print("AUC on new split:", metric_for_churn(y_oot2, prob2))

AUC on new split: 0.989